# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: BinaryMark.RandomItemPicker
PackageVersion: 3.5
PackageLocale: en-US
Publisher: BinaryMark
PublisherUrl: https://www.binarymark.com/?ref=winget
PublisherSupportUrl: https://www.binarymark.com/support?ref=winget
PrivacyUrl: https://www.binarymark.com/about/privacy-policy?ref=winget
Author: BinaryMark
PackageName: "Random Item Picker Free Edition"
PackageUrl: "https://www.binarymark.com/products/random-item-picker"
License: EULA
LicenseUrl: https://www.binarymark.com/about/eula?ref=winget
Copyright: Copyright (C) 2021 BinaryMark
CopyrightUrl: https://www.binarymark.com/about/eula?ref=winget
ShortDescription: "Randomly pick items and remove duplicates from large lists. Different probabilities can be assigned to each item and items can be picked in groups or individually. There is ability to pick same items multiple times, sort and shuffle lists, and more!"
Description: "Randomly pick items and remove duplicates from large lists with thousands of entries. Different probabilities can be assigned to each item and items can be picked in groups or individually. There are many options and commands, including the ability to pick same items multiple times, randomizing and equalizing the chances, sorting, shuffling and much more! Program supports easy export and import to/from text files and other programs, and has full clipboard support. The product is ideal for randomly selecting people - students or employees for various tests, like drug tests for example. You can also use the product whenever you need to take a random sample or make a subset out of a bigger set."
Moniker: "random-item-picker"
Tags:
- random-sampling
- random-choosing
- select
- pick
- random
- choice
- test
- statistics
- shuffle-list
- sort
- random-list
- item
- pick-at-random
- randomized-selection
ManifestType: defaultLocale
ManifestVersion: 1.10.0