PackageIdentifier: BinaryMark.ColorPickerPro
PackageVersion: 3.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: "https://download.binarymark.com/packages/pid0110300t.exe"
  InstallerSha256: e0567ffc5c398b905472feaa985239c7007f624d6ffd7c2aba3853918b15cc62
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: "https://download.binarymark.com/packages/pid0110300t.exe"
  InstallerSha256: e0567ffc5c398b905472feaa985239c7007f624d6ffd7c2aba3853918b15cc62
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0